import type { DiscoveryFinding, Report, Vulnerability, VulnerabilityType } from '@sentinel-x/contracts';

export interface VerificationResult {
  status: 'verified' | 'false_positive';
  confidenceScore: number;
  fvHarness: string;
  fvLog: string;
  counterExample?: string | null;
}

const MIN_SNIPPET = 8;
const VERIFY_FLOOR = 0.62;

export function verifyFinding(
  finding: DiscoveryFinding,
  options: { adapterBoost?: number; adapterLog?: string } = {},
): VerificationResult {
  const harness = buildHarness(finding);
  const hasConcreteSnippet = Boolean(finding.pocCode && finding.pocCode.trim().length >= MIN_SNIPPET);
  const hasLocation = Boolean(finding.affectedFile && finding.lineNumber);
  const hasRule = Boolean(finding.ruleId || finding.fingerprint);
  const structural = [hasConcreteSnippet, hasLocation, hasRule].filter(Boolean).length;
  const boostedConfidence = Math.min(0.99, finding.confidenceScore + (options.adapterBoost ?? 0));
  const highConfidence = boostedConfidence >= VERIFY_FLOOR;
  const verified = highConfidence && structural >= 2;
  const adapterNote = options.adapterLog ? ` Adapters: ${options.adapterLog}` : '';

  return {
    status: verified ? 'verified' : 'false_positive',
    confidenceScore: verified
      ? Math.min(0.97, boostedConfidence + 0.06 + structural * 0.01)
      : Math.max(0.15, boostedConfidence - 0.22),
    fvHarness: harness,
    fvLog: verified
      ? `Bounded defensive verification accepted finding (structural=${structural}/3, rule=${finding.ruleId ?? 'n/a'}).${adapterNote} Operator must validate on live scope.`
      : `Finding failed structural/confidence gate (structural=${structural}/3).${adapterNote} Downgraded to false positive.`,
    counterExample: verified ? finding.pocCode ?? null : null,
  };
}

function buildHarness(finding: DiscoveryFinding): string {
  return [
    '# Sentinel-X defensive verification harness',
    `rule_id: ${finding.ruleId ?? 'legacy'}`,
    `fingerprint: ${finding.fingerprint ?? 'n/a'}`,
    `vuln_type: ${finding.vulnType}`,
    `assertion: ${finding.title}`,
    `file: ${finding.affectedFile ?? 'unknown'}`,
    `line: ${finding.lineNumber ?? 'unknown'}`,
    `function: ${finding.affectedFunction ?? 'unknown'}`,
    'mode: bounded-structural',
    'policy: never auto-submit to bounty platforms',
  ].join('\n');
}

export function buildImmunefiReport(vulnerability: Vulnerability): Report {
  const markdown = [
    `# ${vulnerability.title}`,
    '',
    '## Brief/Intro',
    vulnerability.description,
    '',
    '## Vulnerability Details',
    `- Severity: **${vulnerability.severity}**`,
    `- Type: \`${vulnerability.vulnType}\``,
    `- Target language: \`${vulnerability.targetLanguage}\``,
    vulnerability.ruleId ? `- Rule: \`${vulnerability.ruleId}\`` : null,
    vulnerability.fingerprint ? `- Fingerprint: \`${vulnerability.fingerprint}\`` : null,
    vulnerability.affectedFile ? `- Affected file: \`${vulnerability.affectedFile}\`` : null,
    vulnerability.affectedFunction ? `- Affected function: \`${vulnerability.affectedFunction}\`` : null,
    vulnerability.lineNumber ? `- Line: ${vulnerability.lineNumber}` : null,
    vulnerability.confidenceScore != null
      ? `- Confidence: ${(vulnerability.confidenceScore * 100).toFixed(1)}%`
      : null,
    '',
    '## Impact',
    impactFor(vulnerability.severity),
    '',
    '## Proof of Concept',
    '```',
    vulnerability.pocCode ?? 'No captured snippet.',
    '```',
    '',
    '## Recommendation',
    recommendationFor(vulnerability.vulnType),
    '',
    vulnerability.fvHarness
      ? ['## Verification Harness', '```', vulnerability.fvHarness, '```'].join('\n')
      : null,
    vulnerability.counterExample
      ? ['## Counterexample', '```', vulnerability.counterExample, '```'].join('\n')
      : null,
    '',
    '_Generated by Sentinel-X AVR in defensive research mode. Operator must validate on live scope before submission._',
  ]
    .filter(Boolean)
    .join('\n');

  return {
    vulnerabilityId: vulnerability.id,
    markdown,
    title: vulnerability.title,
    severity: vulnerability.severity,
    generatedAt: new Date().toISOString(),
  };
}

function impactFor(severity: Vulnerability['severity']): string {
  switch (severity) {
    case 'critical':
      return 'Critical integrity break with direct fund or proof forgery potential.';
    case 'high':
      return 'High-severity lane that can break authorization or proof soundness under realistic inputs.';
    case 'medium':
      return 'Material weakness requiring targeted exploitation conditions.';
    case 'low':
      return 'Limited but real correctness or safety degradation.';
    default:
      return 'Informational hardening opportunity.';
  }
}

function recommendationFor(vulnType: VulnerabilityType): string {
  switch (vulnType) {
    case 'under_constrained_circuit':
      return 'Bind every private witness to public claims with explicit assertions and negative tests.';
    case 'integer_overflow':
      return 'Use checked arithmetic or explicit bounds and add regression tests around edge values.';
    case 'cpi_vulnerability':
      return 'Constrain CPI targets with signer, owner, and has_one checks before invocation.';
    case 'uninitialized_account':
      return 'Require payer, space, and seed bindings on every init path.';
    case 'reentrancy':
      return 'Complete state updates before CPI, or use checks-effects-interactions with reentrancy guards.';
    case 'access_control':
      return 'Enforce signer/owner constraints and document unsafe invariants with adversarial tests.';
    case 'arithmetic_error':
      return 'Guard denominators and prove domain constraints before Field division.';
    default:
      return 'Add explicit invariants, negative tests, and independent review before mainnet or bounty submission.';
  }
}
